# Generated by Django 3.1.2 on 2021-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swlab4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='client',
            name='token_generation_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
